## NumPy

**NumPy** — библиотека языка Python, позволяющая [удобно] работать с многомерными массивами и матрицами, содержащая математические функции. Кроме того, NumPy позволяет векторизовать многие вычисления, имеющие место в машинном обучении.

 - [numpy](http://www.numpy.org)
 - [numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/)
 - [100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)

In [1]:
from numpy import array
from numpy import empty
from numpy import zeros
from numpy import ones
from numpy import vstack, hstack

Основным типом данных NumPy является многомерный массив элементов одного типа — [numpy.ndarray](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.array.html). Каждый подобный массив имеет несколько *измерений* или *осей* — в частности, вектор (в классическом понимании) является одномерным массивом и имеет 1 ось, матрица является двумерным массивом и имеет 2 оси и т.д.

In [2]:
# create array
l = [1.0, 2.0, 3.0]
a = array(l)

# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


an empty 3  3 two-dimensional array:

In [3]:
a = empty([3,3])
print(a)

[[ 6.17779239e-31 -1.23555848e-30  3.08889620e-31]
 [-1.23555848e-30  2.68733969e-30 -8.34001973e-31]
 [ 3.08889620e-31 -8.34001973e-31  4.78778910e-31]]


The argument to the function is an array or tuple that species the length of each
dimension of the array to create. The example below creates a 3  5 zero two-dimensional array:

In [4]:
import numpy as np

In [5]:
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


The example below creates a 5-element one-dimensional array

In [6]:
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


In [7]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создание последовательностей при помощи функций arange (в качестве параметров принимает левую и правую границы последовательности и **шаг**) и linspace (принимает левую и правую границы и **количество элементов**):

In [8]:
np.arange(2, 20, 3) # аналогично стандартной функции range python, правая граница не включается

array([ 2,  5,  8, 11, 14, 17])

In [9]:
np.arange(2.5, 8.7, 0.9) # но может работать и с вещественными числами

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [10]:
np.linspace(2, 18, 14) # правая граница включается (по умолчанию)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [11]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.ndim # количество осей

2

Чтобы узнать длину массива по каждой из осей, можно воспользоваться атрибутом shape:

In [12]:
mat.shape

(2, 3)

Given two or more existing arrays, you can stack them vertically using the vstack() function:

In [13]:
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
print()
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]

[[1 2 3]
 [4 5 6]]
(2, 3)


Given two or more existing arrays, you can stack them horizontally using the hstack() function:

In [14]:
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3 4 5 6]
(6,)


------------------------
---
----

Converting your data in lists to NumPy arrays:

In [15]:
# list of data
data = [11, 22, 33, 44, 55]
print(data, type(data), sep="\n", end='\n\n')
# array of data
data = array(data)
print(data)
print(type(data))

[11, 22, 33, 44, 55]
<class 'list'>

[11 22 33 44 55]
<class 'numpy.ndarray'>


In [16]:
# list of data
data = [[11, 22], [33, 44], [55, 66]]
print(data, type(data), sep="\n", end='\n\n')
# array of data
data = array(data)
print(data)
print(type(data), end='\n\n')
print(data[2])
print(data[2,1])
print(type(data[2,1]))

[[11, 22], [33, 44], [55, 66]]
<class 'list'>

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>

[55 66]
66
<class 'numpy.int64'>


In [17]:
data = array([ [11, 22],[33, 44],[55, 66] ])
# index data
print(data[0])
print(data[0,])

[11 22]
[11 22]


One-Dimensional Slicing:

In [18]:
data = array([11, 22, 33, 44, 55, 66, 77, 88, 99, 00])
print(data[1::2])

[22 44 66 88  0]


Two-Dimensional Slicing:

In [19]:
data = array([ [11, 22, 33],[44, 55, 66],[77, 88, 99],[11,44,77],[22,55,88],[33,66,99] ])
print("data:\n", data, end='\n\n')
# separate data
x, y, z = data[:, :-1], data[:, -1], data[1:4:2]
print("x:\n", x)
print()
print("y:\n", y)
print()
print("z:\n", z)

data:
 [[11 22 33]
 [44 55 66]
 [77 88 99]
 [11 44 77]
 [22 55 88]
 [33 66 99]]

x:
 [[11 22]
 [44 55]
 [77 88]
 [11 44]
 [22 55]
 [33 66]]

y:
 [33 66 99 77 88 99]

z:
 [[44 55 66]
 [11 44 77]]


In [20]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [21]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [22]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [23]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

It is common to split a loaded dataset into separate train and test sets.
This would involve slicing all columns by specifying :in the second dimension index. 
The training dataset would be all rows from the beginning to the split point:

In [24]:
data = array([
[10, 20, 30],
[111, 222, 333],
[40, 50, 60],
[444, 555, 666],
[70, 80, 90],
[777, 888, 989]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train, end="\n\n")
print(test)

[[ 10  20  30]
 [111 222 333]]

[[ 40  50  60]
 [444 555 666]
 [ 70  80  90]
 [777 888 989]]


In [25]:
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 6
Cols: 3


Reshape 1D to 2D Array:

In [26]:
data = array([11, 22, 33, 44, 55])
print(data)
print(data.shape)
print()
# reshape
data = data.reshape((data.shape[0], 1))
print(data)
print(data.shape)

[11 22 33 44 55]
(5,)

[[11]
 [22]
 [33]
 [44]
 [55]]
(5, 1)


In [27]:
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data)
print(data.shape)
print('----------')
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1, 1))
print(data)
print(data.shape)

[[11 22]
 [33 44]
 [55 66]]
(3, 2)
----------
[[[[11]]

  [[22]]]


 [[[33]]

  [[44]]]


 [[[55]]

  [[66]]]]
(3, 2, 1, 1)


------
---
---

#### Базовые операции

* Базовые арифметические операции над массивами выполняются поэлементно:

In [28]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)

In [29]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [31]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [32]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [33]:
a = array([1, 2, 3])
b = array([1, 2, 3])
c = a + b
print(c)

[2 4 6]


Поскольку операции выполняются поэлементно, операнды бинарных операций должны иметь одинаковый размер. Тем не менее, операция может быть корректно выполнена, если размеры операндов таковы, что они могут быть расширены до одинаковых размеров. Данная возможность называется [broadcasting](http://www.scipy-lectures.org/intro/numpy/operations.html#broadcasting):
![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

Broadcasting is the name given to the method that NumPy uses to allow array arithmetic
between arrays with a dierent shape or size.

Broadcasting between scalar and one-dimensional array:

In [34]:
# define array
a = array([1, 2, 3])
print(a)
# define scalar
b = 2
print(b)
# broadcast
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


Broadcasting between scalar and two-dimensional array:

In [35]:
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define scalar
b = 10
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [4 5 6]]
10
[[11 12 13]
 [14 15 16]]


Broadcasting between one-dimensional and two-dimensional arrays:

In [36]:
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define one-dimensional array
b = array([-1, -2, -3])
print(b)
# broadcast
C = A + b
print(C)

bb = array([-1, -2])
#C = A + bb - Error

[[1 2 3]
 [4 5 6]]
[-1 -2 -3]
[[0 0 0]
 [3 3 3]]


In [37]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
A.min()

1

In [39]:
A.max(axis=1)

array([3, 6])

In [40]:
A.sum(axis=1)

array([ 6, 15])

---
----
---

#### Зачем?

Зачем необходимо использовать NumPy, если существуют стандартные списки/кортежи и циклы?

Причина заключается в скорости работы. Попробуем посчитать скалярное произведение 2 больших векторов:

In [41]:
SIZE = 10000000

A_quick_arr = np.random.normal(size = (SIZE,))
B_quick_arr = np.random.normal(size = (SIZE,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [42]:
%%time
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]

CPU times: user 4.53 s, sys: 31.1 ms, total: 4.56 s
Wall time: 4.97 s


In [43]:
%%time
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(SIZE)])

CPU times: user 2.87 s, sys: 214 ms, total: 3.08 s
Wall time: 3.16 s


In [44]:
%%time
ans = np.sum(A_quick_arr * B_quick_arr)

CPU times: user 42.4 ms, sys: 39.2 ms, total: 81.6 ms
Wall time: 81.2 ms


In [45]:
%%time
ans = A_quick_arr.dot(B_quick_arr)

CPU times: user 15.5 ms, sys: 1.8 ms, total: 17.3 ms
Wall time: 11.5 ms


---
----
---

The $L_1$ norm of a vector can be calculated in NumPy using the `norm()` function with a
parameter to specify the norm order, in this case 1:

In [46]:
from numpy.linalg import norm

a = array([1, 2, 3])
print(a)

l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


The $L_2$ norm of a vector can be calculated in NumPy using the `norm()` function with default
parameters:

In [47]:
a = array([1, 3, 4])
print(a)

l2 = norm(a)
print(l2)

[1 3 4]
5.0990195135927845


The length of a vector can be calculated using the maximum norm, also called max norm. Max
norm of a vector is referred to as $L^{\infty}$.
<br>The max norm of a vector can be calculated in NumPy using the `norm()` function with the
order parameter set to inf:

In [48]:
from math import inf

a = array([1, 2, 3])
print(a)

maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0


Норма по строчкам:

In [49]:
a = array([ [1, 2, 3], [3, 4, 5]])
print(a)

max_norm = norm(a, inf)
print(max_norm)

[[1 2 3]
 [3 4 5]]
12.0


In [50]:
a = a.reshape(3, 2)
print(a)

max_norm = norm(a, inf)
print(max_norm)

[[1 2]
 [3 3]
 [4 5]]
9.0


In [51]:
a = array([ [1, 2, 3], [3, 4, 5]])
print(a)

ell2 = norm(a)
print(ell2)

[[1 2 3]
 [3 4 5]]
8.0


Норма по столбцам:

In [52]:
a = array([ [1, 2, 3], [3, 4, 5]])
print(a)

ell1 = norm(a, 1)
print(ell1)

[[1 2 3]
 [3 4 5]]
8.0


In [53]:
a = a.reshape(3, 2)
print(a)

ell1 = norm(a, 1)
print(ell1)

[[1 2]
 [3 3]
 [4 5]]
10.0


NumPy provides functions to calculate a triangular matrix from an existing square matrix.
The `tril()` function to calculate the lower triangular matrix from a given matrix and the
triu() to calculate the upper triangular matrix from a given matrix:

In [54]:
from numpy import tril
from numpy import triu

M = array([
        [1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]
         ])
print(M)
print('-----')

# lower triangular matrix
lower = tril(M)
print(lower)
print('-----')
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [3 4 5]
 [5 6 7]]
-----
[[1 0 0]
 [3 4 0]
 [5 6 7]]
-----
[[1 2 3]
 [0 4 5]
 [0 0 7]]


NumPy provides the function `diag()` that can create a diagonal matrix from an existing
matrix, or transform a vector into a diagonal matrix:

In [55]:
from numpy import diag

M = array([
        [1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]
         ])
print(M)
print('-----')

# extract diagonal vector
d = diag(M)
print(d)
print('-----')
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [3 4 5]
 [5 6 7]]
-----
[1 4 7]
-----
[[1 0 0]
 [0 4 0]
 [0 0 7]]


In [56]:
# orthogonal matrix
from numpy.linalg import inv

# define orthogonal matrix
Q = array([
        [1, 0],
        [0, -1]
         ])
print(Q)
print('-----')

# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)
print('-----')

# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
-----
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
-----
[[1 0]
 [0 1]]


-------
-------
-----

In [57]:
from numpy.linalg import det

A = array([
    [1, 2, 3],
    [3, 2, 1],
    [-1, 2, 3]])

B = det(A)
B

7.999999999999998

In [58]:
from numpy.linalg import matrix_rank

v1 = array([1,2,3])
vr1 = matrix_rank(v1)
print(vr1)

v2 = array([0,0,0,0,0])
vr2 = matrix_rank(v2)
print(vr2)

1
0


A **sparse matrix** is a matrix that is comprised of mostly zero values.
<br>The **sparsity** of a matrix can be quantied with a score, which is the number of zero values
in the matrix divided by the total number of elements in the matrix.

The solution to representing and working with sparse matrices is to use an alternate data
structure to represent the sparse data. The zero values can be ignored and only the data or
non-zero values in the sparse matrix need to be stored or acted upon. There are multiple data
structures that can be used to eciently construct a sparse matrix; three common examples are
listed below.

- **Dictionary of Keys**. A dictionary is used where a row and column index is mapped to
a value.
- **List of Lists**. Each row of the matrix is stored as a list, with each sublist containing the
column index and the value.
- **Coordinate List**. A list of tuples is stored with each tuple containing the row index,
column index, and the value.

SciPy provides tools for creating sparse matrices using multiple data structures, as well as
tools for converting a dense matrix to a sparse matrix. Many linear algebra NumPy and
SciPy functions that operate on NumPy arrays can transparently operate on SciPy sparse
arrays.

A dense matrix stored in a NumPy array can be converted into a sparse matrix using the
CSR representation by calling the csr matrix() function

In [59]:
# sparse matrix
from numpy import array
from scipy.sparse import csr_matrix

# create dense matrix
A = array([
[1, 0, 0, 1, 0, 0],
[0, 0, 2, 0, 0, 1],
[0, 0, 0, 2, 0, 0]])
print(A)
print('-----')

# convert to sparse matrix (CSR method)
S = csr_matrix(A)
print(S)
print('-----')

# reconstruct dense matrix
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
-----
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
-----
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [60]:
sparsity = 1.0 - np.count_nonzero(A) / A.size
sparsity

0.7222222222222222

-------
-------
-----

Many complex matrix operations cannot be solved eciently or with stability using the limited
precision of computers. **Matrix decompositions** are methods that reduce a matrix into constituent
parts that make it easier to calculate more complex matrix operations. Matrix decomposition
methods, also called matrix factorization methods, are a foundation of linear algebra in computers,
even for basic operations such as solving systems of linear equations, calculating the inverse, and
calculating the determinant of a matrix.

The LU decomposition is for square matrices and decomposes a matrix into L and U components.
$$A = LU$$ 
Where A is the square matrix that we wish to decompose, L is the lower triangle matrix
and U is the upper triangle matrix.

The LU decomposition is found using an iterative numerical process and can fail for those
matrices that cannot be decomposed or decomposed easily. A variation of this decomposition
that is numerically more stable to solve in practice is called the LUP decomposition, or the LU
decomposition with partial pivoting.
$$A = LUP$$
The rows of the parent matrix are re-ordered to simplify the decomposition process and the
additional P matrix specifies a way to permute the result or return the result to the original
order

In [61]:
from numpy import array
from scipy.linalg import lu


A = array([
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
P, L, U = lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]


In [63]:
# reconstruct
B = P.dot(L).dot(U)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


The QR decomposition is for n  m matrices (not limited to square matrices) and decomposes
a matrix into Q and R components.
$$A = QR$$
Where A is the matrix that we wish to decompose, Q a matrix with the size $m \times m$, and R is
an upper triangle matrix with the size $m \times n$. The QR decomposition is found using an iterative
numerical method that can fail for those matrices that cannot be decomposed, or decomposed
easily. Like the LU decomposition, the QR decomposition is often used to solve systems of
linear equations, although is not limited to square matrices.

In [64]:
from numpy import array
from numpy.linalg import qr


A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [65]:
Q, R = qr(A, 'complete')
print(Q)
print(R)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [66]:
# reconstruct
B = Q.dot(R)
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


The Cholesky decomposition is for square symmetric matrices where all values are greater than
zero, so-called positive definite matrices.
$$A = LL^T$$
Where A is the matrix being decomposed, $L$ is the lower triangular matrix and $L^T$ is the
transpose of $L$.

The Cholesky decomposition is used for solving
linear least squares for linear regression, as well as simulation and optimization methods. When
decomposing symmetric matrices, the Cholesky decomposition is nearly twice as ecient as the
LU decomposition and should be preferred in these cases.

In [67]:
from numpy import array
from numpy.linalg import cholesky


A = array([
[2, 1, 1],
[1, 2, 1],
[1, 1, 2]])
print(A)

[[2 1 1]
 [1 2 1]
 [1 1 2]]


In [68]:
L = cholesky(A)
print(L)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


In [69]:
# reconstruct
B = L.dot(L.T)
print(B)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


---
---
---

Matrix decompositions are a useful tool for reducing a matrix to their constituent parts in
order to simplify a range of more complex operations. Perhaps the most used type of matrix
decomposition is the eigendecomposition that decomposes a matrix into eigenvectors and
eigenvalues. This decomposition also plays a role in methods used in machine learning, such
as in the Principal Component Analysis method or PCA.

Eigendecomposition of a matrix is a type of decomposition that involves decomposing a square
matrix into a set of eigenvectors and eigenvalues.

A matrix could have one eigenvector and eigenvalue for each dimension of the parent matrix.
Not all square matrices can be decomposed into eigenvectors and eigenvalues, and some can
only be decomposed in a way that requires complex numbers. The parent matrix can be shown
to be a product of the eigenvectors and eigenvalues.
$$A = Q \Lambda Q^T$$
Where $Q$ is a matrix comprised of the eigenvectors, $\Lambda$ is the uppercase Greek letter lambda
and is the diagonal matrix comprised of the eigenvalues, and $Q^T$ is the transpose of the matrix
comprised of the eigenvectors.

In [70]:
from numpy import array
from numpy.linalg import eig


A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
values, vectors = eig(A)
print(values)
print()
print(vectors)

[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [72]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig


A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
values, vectors = eig(A)

# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [74]:
# reconstruct matrix
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig


A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


---

Perhaps the most known and widely used matrix decomposition
method is the Singular-Value Decomposition, or SVD. All matrices have an SVD, which makes
it more stable than other methods, such as the eigendecomposition. As such, it is often used
in a wide array of applications including compressing, denoising, and data reduction.

The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for
reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations
simpler. For the case of simplicity we will focus on the SVD for real-valued matrices and ignore
the case for complex numbers.
$$A = U \ \Sigma \ V^T$$ 
Where A is the real $n \times m$ matrix that we wish to decompose, U is an $m \times m$ matrix, $\Sigma$
represented by the uppercase Greek letter sigma) is an $m \times n$ diagonal matrix, and $V^T$ is the V
transpose of an $n \times n$ matrix where T is a superscript.

The SVD is calculated via iterative numerical
methods. We will not go into the details of these methods.

In [76]:
from numpy import array
from scipy.linalg import svd


A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [77]:
U, s, V = svd(A)
print(U)
print()
print(s)
print()
print(V)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

[9.52551809 0.51430058]

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [78]:
# reconstruct rectangular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd


A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [79]:
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


A popular application of SVD is for dimensionality reduction. Data with a large number of
features, such as more features (columns) than observations (rows) may be reduced to a smaller
subset of features that are most relevant to the prediction problem. The result is a matrix with
a lower rank that is said to approximate the original matrix. To do this we can perform an SVD
operation on the original data and select the top k largest singular values in $\Sigma$. These columns
can be selected from $\Sigma$ and the rows selected from $V^T$ . An approximate B of the original vector
A can then be reconstructed.
$$B = U \ \Sigma_k \ V_k^T$$

In practice, we can retain and work with a descriptive subset of the data called T.
This is a dense summary of the matrix or a projection.
<br>$T = U \ \Sigma_k$

In [80]:
# data reduction with svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd


A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [81]:
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements, :]

# reconstruct
B = U.dot(Sigma.dot(V))
print(B)
print()

# transform
T = U.dot(Sigma)
print(T)
print()
T = A.dot(V.T)
print(T)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [82]:
# svd data reduction in scikit-learn
from numpy import array
from sklearn.decomposition import TruncatedSVD


A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [83]:
# create transform
svd = TruncatedSVD(n_components=2)
# fit transform
svd.fit(A)
# apply transform
result = svd.transform(A)
print(result)

[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
