In [1]:
print("Is it greater?", 5 > -2)

Is it greater? True


In [2]:
print("Is it greater or equal?", 5 >= -2)

Is it greater or equal? True


In [3]:
print("What is 5 - 7?", 5 - 7)

What is 5 - 7? -2


In [7]:
print(3 + 0 < 15 - 7)

True


In [13]:
print(15 % 7)

1


In [2]:
my_name = 'Zed A. Shaw'
my_age = 35

In [6]:
print(f"Let's talk about {my_name}.")
print(f"He's {my_age} years old.")

Let's talk about Zed A. Shaw.
He's 35 years old.


In [9]:
# this one is like your scripts with argv
def print_two(*args):
    arg1, arg2 = args
    print(f"arg1: {arg1}, arg2: {arg2}")
# ok, that *args is actually pointless, we can just do this
def print_two_again(arg1, arg2):
    print(f"arg1: {arg1}, arg2: {arg2}")

In [10]:
print_two("Zed","Shaw")
print_two_again("Zed","Shaw")

arg1: Zed, arg2: Shaw
arg1: Zed, arg2: Shaw


In [26]:
def test_addition(a, b):
    print("I:", a, b)
    a *= 2
    b -= 3
    print("II:", a, b)
    return a+b

In [27]:
a = 2
b = 3
print(test_addition(a, b))
print("III:", a, b)

I: 2 3
II: 4 0
4
III: 2 3


In [7]:
x = 1.235
format(x, '0.2f')

'1.24'

In [10]:
from decimal import Decimal
from decimal import localcontext

a = Decimal('1.3')
b = Decimal('1.7')
print(a / b)

with localcontext() as ctx:
    ctx.prec = 3
    print(a / b)

0.7647058823529411764705882353
0.765


In [13]:
a = Decimal('4.2')
b = Decimal('2.1')
print(a + b)
print((a + b) == Decimal('6.3'))

6.3
True


In [14]:
a = 4.2
b = 2.1
print(a + b)
print((a + b) == 6.3)

6.300000000000001
False


In [19]:
a=b=c=d=e=f = 1234.56789

# Two decimal places of accuracy
print(format(a, '0.2f'))
# Right justified in 10 chars, one-digit accuracy
print(format(b, '>10.1f'))
# Left justified
print(format(c, '<10.1f'))
# Centered
print(format(d, '^10.1f'))
# Inclusion of thousands separator
print(format(e, ','))
print(format(f, '0,.1f'))

1234.57
    1234.6
1234.6    
  1234.6  
1,234.56789
1,234.6


In [24]:
import numpy as np

a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
print(a)

[2.+3.j 4.+5.j 6.-7.j 8.+9.j]


In [22]:
import cmath

print(cmath.sqrt(-1))

1j


In [25]:
from fractions import Fraction

a = Fraction(5, 4)
b = Fraction(7, 16)
print(a + b)
print(a * b)

# Getting numerator/denominator
c = a * b
print(c.numerator)
print(c.denominator)

27/16
35/64
35
64


In [31]:
# The major feature of NumPy is that it gives Python an array object that is much more efficient 
# and better suited for mathematical calculation than a standard Python list.

# Python lists
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
print(x * 2)
# print(x + 10)  -  error
print(x + y)
print()

[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7, 8]



In [36]:
# Numpy arrays
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
print(ax * 2)
print(ax + 10)
print(ax + ay)
print(ax * ay, end="\n\n")

def f(x):
    return 3*x**2 - 2*x + 7
print(f(ax))

[2 4 6 8]
[11 12 13 14]
[ 6  8 10 12]
[ 5 12 21 32]

[ 8 15 28 47]


In [41]:
#if you want to make a two-dimensional grid of 10,000 by 10,000 floats, it’s not an issue:
grid = np.zeros(shape=(10000,10000), dtype=float)
print(grid, end='\n\n')

grid += 10
print(grid)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

[[10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 ...
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]]


In [56]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
print(a[0])
print(a[:0])
print(a[:1])
print(a[:,0])

[1 2 3 4]
[]
[[1 2 3 4]]
[1 5 9]


In [58]:
print(a[1:3, 1:3], end='\n\n')
a[1:3, 1:3] += 10
print(a)

[[ 6  7]
 [10 11]]

[[ 1  2  3  4]
 [ 5 16 17  8]
 [ 9 20 21 12]]


In [60]:
# Conditional assignment on an array
print(np.where(a < 10, a, -10))

[[  1   2   3   4]
 [  5 -10 -10   8]
 [  9 -10 -10 -10]]


In [67]:
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
print(m, end='\n\n')
print(m.T, end='\n\n')

[[ 1 -2  3]
 [ 0  4  5]
 [ 7  8 -9]]

[[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]



In [85]:
mn = np.matrix([[4,0,0],[0,5,0],[0,0,-8]])
print(mn, end='\n\n')
print(np.linalg.det(mn), end='\n\n')
print(mn.I, end='\n\n')
print(mn)

[[ 4  0  0]
 [ 0  5  0]
 [ 0  0 -8]]

-159.99999999999994

[[ 0.25   0.     0.   ]
 [ 0.     0.2    0.   ]
 [-0.    -0.    -0.125]]

[[ 4  0  0]
 [ 0  5  0]
 [ 0  0 -8]]


In [88]:
import random

values = [1, 2, 3, 4, 5, 6]
print(random.choice(values))
print(random.choice(values))
print()

print(random.sample(values, 3))

4
2

[2, 1, 3]


In [100]:
from datetime import timedelta

a = timedelta(days=2, hours=6)
b = timedelta(hours=4.5)
c = a + b

print(c.days)
print(c.seconds)
print(c.seconds / 3600)
print(c.total_seconds() / 3600)

2
37800
10.5
58.5


In [101]:
from datetime import datetime

a = datetime(2012, 9, 23)
print(a + timedelta(days=10))
print()
b = timedelta(2012, 9, 23)
print(b + timedelta(days=10))

2012-10-03 00:00:00

2022 days, 0:00:09.000023


In [1]:
l = [1, 3, 2, 5, 4]
l.sort()
print(l)

[1, 2, 3, 4, 5]


In [2]:
l = l.sort()
print(l)

None


In [8]:
l2 = [1, 3, 2, 5, 4]
sorted(list_of_words)

['', 'dict', 'list', 'one', 'two']

In [4]:
def intro(**data):
    print("\nData type of argument:", type(data))
    
    for key, value in data.items():
        print(f"{key} is {value}")
        
intro(firstName="Sita", lastName="Sharma", age=22, phone=103975)
intro(firstName="John", lastName="Wood", email="johnwood@mail.mail", country="sa")


Data type of argument: <class 'dict'>
firstName is Sita
lastName is Sharma
age is 22
phone is 103975

Data type of argument: <class 'dict'>
firstName is John
lastName is Wood
email is johnwood@mail.mail
country is sa


In [ ]:
def adder(*nums):
    sum = 0
    for i in nums:
        sum += n
    print(sum)
    
adder(3, 5)
adder(2, 4, 6)